export const strings = {
  app: {
    name: 'FinControl',
    mobileName: 'FinControl Mobile',
    tagline: 'Controle financeiro pessoal na palma da mão.',
    demoHint: 'Conecte sua API para usar seus dados reais no celular.',
  },
  auth: {
    welcomeEyebrow: 'Aplicativo oficial',
    welcomeTitle: 'Sua rotina financeira, agora no celular.',
    welcomeBody:
      'Acompanhe saldo, lançamentos, metas e relatórios em uma experiência mais direta, pensada para consulta e organização rápida.',
    loginTitle: 'Entrar',
    loginBody: 'Use o email e a senha da sua conta FinControl.',
    registerTitle: 'Criar conta',
    registerBody: 'Abra seu acesso pelo celular e continue no painel web quando quiser.',
    accessButton: 'Acessar',
    createAccountButton: 'Criar conta',
    backToAccess: 'Voltar ao acesso',
    loginSuccess: 'Sessão iniciada com sucesso.',
    registerSuccess: 'Conta criada com sucesso.',
    logoutSuccess: 'Sessão encerrada.',
  },
  fields: {
    name: 'Nome',
    email: 'Email',
    password: 'Senha',
    apiUrl: 'URL da API',
    search: 'Busca',
    amount: 'Valor',
    type: 'Tipo',
    initialBalance: 'Saldo inicial',
    description: 'Descrição',
    transactionDate: 'Data',
    notes: 'Observações',
    color: 'Cor',
    targetAmount: 'Valor alvo',
    title: 'Título',
    account: 'Conta',
    category: 'Categoria',
  },
  modules: {
    overview: 'Visão geral',
    accounts: 'Contas',
    transactions: 'Lançamentos',
    categories: 'Categorias',
    goals: 'Metas',
    reports: 'Relatórios',
    settings: 'Configurações',
  },
  overview: {
    title: 'Panorama do mês',
    subtitle: 'Resumo rápido do que realmente importa no dia.',
    totalBalance: 'Patrimônio consolidado',
    income: 'Receitas do mês',
    expense: 'Despesas do mês',
    net: 'Saldo do mês',
    quickAccess: 'Acesso rápido',
    recentTransactions: 'Últimos lançamentos',
    emptyTransactions: 'Nenhum lançamento encontrado até agora.',
    emptyGoal: 'Nenhuma meta ativa no momento.',
  },
  accounts: {
    title: 'Contas financeiras',
    subtitle: 'Saldos sincronizados com o backend.',
    createTitle: 'Nova conta',
    editTitle: 'Editar conta',
    createAction: 'Cadastrar conta',
    editAction: 'Salvar alterações',
    empty: 'Nenhuma conta cadastrada ainda.',
    inactiveBadge: 'Inativa',
    deactivateAction: 'Inativar',
    deactivateConfirm: 'Deseja inativar esta conta? Ela deixará de aparecer como opção ativa nos lançamentos.',
  },
  transactions: {
    title: 'Lançamentos',
    subtitle: 'Movimentações mais recentes da sua conta.',
    createTitle: 'Novo lançamento',
    editTitle: 'Editar lançamento',
    createAction: 'Registrar lançamento',
    editAction: 'Salvar alterações',
    deleteAction: 'Excluir',
    deleteConfirm: 'Deseja excluir este lançamento?',
    empty: 'Nenhum lançamento disponível.',
    income: 'Receita',
    expense: 'Despesa',
    all: 'Todos',
    filtersTitle: 'Filtros rápidos',
    searchPlaceholder: 'Buscar por descrição, conta ou categoria',
    resultsTitle: 'Movimentações encontradas',
    dependencyHint: 'Cadastre ao menos uma conta ativa e uma categoria compatível para lançar.',
    uncategorized: 'Sem categoria',
    unaccounted: 'Sem conta',
  },
  categories: {
    title: 'Categorias',
    subtitle: 'Classificações usadas no seu fluxo financeiro.',
    createTitle: 'Nova categoria',
    editTitle: 'Editar categoria',
    createAction: 'Cadastrar categoria',
    editAction: 'Salvar alterações',
    deleteAction: 'Excluir',
    deleteConfirm: 'Deseja excluir esta categoria?',
    empty: 'Nenhuma categoria cadastrada.',
  },
  goals: {
    title: 'Metas',
    subtitle: 'Objetivos e limites acompanhados no sistema.',
    createTitle: 'Nova meta',
    editTitle: 'Editar meta',
    createAction: 'Cadastrar meta',
    editAction: 'Salvar alterações',
    deleteAction: 'Excluir',
    deleteConfirm: 'Deseja excluir esta meta?',
    empty: 'Nenhuma meta registrada.',
    saving: 'Meta de economia',
    limit: 'Limite de gasto',
    snapshotTitle: 'Acompanhamento atual',
  },
  reports: {
    title: 'Relatórios',
    subtitle: 'Leitura consolidada para consulta rápida no celular.',
    summaryTitle: 'Resumo financeiro',
    categoryDistribution: 'Distribuição por categoria',
    monthlyHistory: 'Histórico mensal',
    notesTitle: 'Observação',
    pdfHint: 'A exportação em PDF continua disponível no painel web.',
    empty: 'Ainda não há dados suficientes para este relatório.',
  },
  settings: {
    title: 'Configurações',
    subtitle: 'API, sincronização e sessão atual.',
    provider: 'Persistência ativa',
    providerUnknown: 'Não identificado',
    checkApi: 'Testar API',
    sync: 'Sincronizar dados',
    logout: 'Sair',
    profileSection: 'Perfil',
    connectionSection: 'Integração',
    mobileHint:
      'Se estiver usando um celular físico, troque a URL da API para um endereço acessível pela sua rede local.',
    apiOnline: 'API respondeu corretamente.',
    apiOffline: 'Não foi possível alcançar a API.',
    syncSuccess: 'Sincronização concluída.',
    apiSaved: 'URL da API atualizada no aplicativo.',
    apiStatus: 'Status da API',
  },
  feedback: {
    fillRequired: 'Preencha todos os campos obrigatórios.',
    positiveAmount: 'Informe um valor maior que zero.',
    sessionExpired: 'Sua sessão expirou. Entre novamente para continuar.',
    saveSuccess: 'Cadastro realizado com sucesso.',
  },
  actions: {
    save: 'Salvar',
    retry: 'Tentar novamente',
    refresh: 'Atualizar',
    open: 'Abrir',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    saving: 'Salvando...',
  },
} as const;

export type Strings = typeof strings;
